# Completion
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']
